[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "robomath"
version = "0.0.1"
authors = [
  { name="David Capacho Parra", email="dcapacho3@gmail.com" },
]
description = "A python library for rotations and 3d transforms and everything else needed for robotic applications."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/dcapacho3/robomath"
Issues = "https://github.com/dcapacho3/robomath/issues"

[dependency-groups]
dev = ["pytest>=8" , "pre-commit>=4.6.2"]
